<?php

namespace eni\QCMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionTirageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTirageRepository extends EntityRepository
{

	public function getQuestionTirage($offset = 0) {

		$qb = $this->createQueryBuilder('qt');

		$qb->setFirstResult($offset)
			->setMaxResults(1);

		return $qb->getQuery()
				  ->getSingleResult();
	}

	public function getQuestionsTirage($inscription) {

		$qb = $this->createQueryBuilder('qt');

		$qb->where('qt.inscription = :inscription')
			->setParameter('inscription', $inscription);

		return $qb->getQuery()
				  ->getResult();
	}
}
