<?php

namespace eni\QCMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
    protected $validator;

    
    public function getRandomQuestionIdsByTheme($nbQuestions, $theme) {
        
        $nbQuestionsByTheme = $theme->getQuestions()->count();

        $idUsed = [];
        for ($i = 0; $i < $nbQuestions; $i++) {
            $randomId = rand(1, intval($nbQuestionsByTheme));
            while (in_array($randomId, $idUsed)) {
                $randomId = rand(1, intval($nbQuestionsByTheme));
            }
            $idUsed[] = $randomId;
        }

        return $idUsed;
    }

    /**
     * @param mixed $validator
     */
    public function setValidator(\Symfony\Component\Validator\Validator $validator)
    {
        $this->validator = $validator;
    }

    /**
     * @return mixed
     */
    public function getValidator()
    {
        if(is_null($this->validator)){
            $ValidatorBuilder = Validation::createValidatorBuilder();
            $ValidatorBuilder->enableAnnotationMapping();
            $this->validator = $ValidatorBuilder->getValidator();
        }
        return $this->validator;
    }

    public function add(Theme $theme){
        $errorsFields = $this->getValidator()->validate($theme);
        if (count($errorsFields) > 0) {
            throw new ExceptionValidation($errorsFields);
        }

        $this->getEntityManager()->persist($theme);
        $this->getEntityManager()->flush();
        return $theme;
    }
}
