parameters:
#    eni_qcm.example.class: eni\QCMBundle\Example

services:
    controller.pre_execute_listener:
        class: eni\QCMBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
