CREATE TABLE utilisateur (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255)
NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL,
 email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHA
R(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NUL
L, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME
DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_a
t DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', cred
entials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL
, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, type VARCHAR(65) NOT
NULL, UNIQUE INDEX UNIQ_1D1C63B392FC23A8 (username_canonical), UNIQUE INDEX UNIQ
_1D1C63B3A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8
 COLLATE utf8_unicode_ci ENGINE = InnoDB;