CREATE TABLE inscriptions (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DE
FAULT NULL, test_id INT DEFAULT NULL, dureeValidite DATETIME NOT NULL, tempsEcou
le DATETIME NOT NULL, etat VARCHAR(20) NOT NULL, resultat INT NOT NULL, INDEX ID
X_74E0281CFB88E14F (utilisateur_id), INDEX IDX_74E0281C1E5D0459 (test_id), PRIMA
RY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE promotions (code_promo VARCHAR(8) NOT NULL, libelle VARCHAR(64) NOT
 NULL, PRIMARY KEY(code_promo)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_
ci ENGINE = InnoDB;
CREATE TABLE questions (id INT AUTO_INCREMENT NOT NULL, enonce LONGTEXT NOT NULL
, media VARCHAR(4096) DEFAULT NULL, type VARCHAR(15) NOT NULL, PRIMARY KEY(id))
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE question_theme (question_id INT NOT NULL, theme_id INT NOT NULL, IN
DEX IDX_A79EF60C1E27F6BF (question_id), INDEX IDX_A79EF60C59027487 (theme_id), P
RIMARY KEY(question_id, theme_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unico
de_ci ENGINE = InnoDB;
CREATE TABLE questions_tirage (id INT AUTO_INCREMENT NOT NULL, question_id INT D
EFAULT NULL, inscription_id INT DEFAULT NULL, estMarquee TINYINT(1) NOT NULL, UN
IQUE INDEX UNIQ_73221F781E27F6BF (question_id), INDEX IDX_73221F785DAC5993 (insc
ription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci
 ENGINE = InnoDB;
CREATE TABLE reponse_donnee (question_tirage_id INT NOT NULL, reponse_proposee_i
d INT NOT NULL, INDEX IDX_5173B9C58B82D4CF (question_tirage_id), INDEX IDX_5173B
9C5755AFC17 (reponse_proposee_id), PRIMARY KEY(question_tirage_id, reponse_propo
see_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE reponses (id INT AUTO_INCREMENT NOT NULL, question_id INT DEFAULT N
ULL, libelle LONGTEXT NOT NULL, estBonne TINYINT(1) NOT NULL, INDEX IDX_1E512EC6
1E27F6BF (question_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8
_unicode_ci ENGINE = InnoDB;
CREATE TABLE sections (id INT AUTO_INCREMENT NOT NULL, theme_id INT DEFAULT NULL
, test_id INT DEFAULT NULL, nbQuestion INT NOT NULL, INDEX IDX_2B96439859027487
(theme_id), INDEX IDX_2B9643981E5D0459 (test_id), PRIMARY KEY(id)) DEFAULT CHARA
CTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE tests (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT N
ULL, nom VARCHAR(64) NOT NULL, description LONGTEXT DEFAULT NULL, duree TIME NOT
 NULL, seuil SMALLINT NOT NULL, UNIQUE INDEX UNIQ_1260FC5E6C6E55B5 (nom), INDEX
IDX_1260FC5EFB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET ut
f8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE themes (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(64) NOT NUL
L, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE =
InnoDB;
ALTER TABLE inscriptions ADD CONSTRAINT FK_74E0281CFB88E14F FOREIGN KEY (utilisa
teur_id) REFERENCES utilisateur (id);
ALTER TABLE inscriptions ADD CONSTRAINT FK_74E0281C1E5D0459 FOREIGN KEY (test_id
) REFERENCES tests (id);
ALTER TABLE question_theme ADD CONSTRAINT FK_A79EF60C1E27F6BF FOREIGN KEY (quest
ion_id) REFERENCES questions (id);
ALTER TABLE question_theme ADD CONSTRAINT FK_A79EF60C59027487 FOREIGN KEY (theme
_id) REFERENCES themes (id);
ALTER TABLE questions_tirage ADD CONSTRAINT FK_73221F781E27F6BF FOREIGN KEY (que
stion_id) REFERENCES questions (id);
ALTER TABLE questions_tirage ADD CONSTRAINT FK_73221F785DAC5993 FOREIGN KEY (ins
cription_id) REFERENCES inscriptions (id);
ALTER TABLE reponse_donnee ADD CONSTRAINT FK_5173B9C58B82D4CF FOREIGN KEY (quest
ion_tirage_id) REFERENCES questions_tirage (id);
ALTER TABLE reponse_donnee ADD CONSTRAINT FK_5173B9C5755AFC17 FOREIGN KEY (repon
se_proposee_id) REFERENCES reponses (id);
ALTER TABLE reponses ADD CONSTRAINT FK_1E512EC61E27F6BF FOREIGN KEY (question_id
) REFERENCES questions (id);
ALTER TABLE sections ADD CONSTRAINT FK_2B96439859027487 FOREIGN KEY (theme_id) R
EFERENCES themes (id);
ALTER TABLE sections ADD CONSTRAINT FK_2B9643981E5D0459 FOREIGN KEY (test_id) RE
FERENCES tests (id);
ALTER TABLE tests ADD CONSTRAINT FK_1260FC5EFB88E14F FOREIGN KEY (utilisateur_id
) REFERENCES utilisateur (id);